export const TOGGLE_COMMENT = 'TOGGLE_COMMENT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';